export const allAdminRoutes = [
	{
	  title: "Dashboard User Acquisition",
	  description: "Analyze user acquisition metrics and track retention strategies effectively.",
	  keyWords: ["dashboard acquisition", "acquisition", "user acquisition", "retention"],
	  route: "/user-dashboards/user-aquisition",
	},
	{
	  title: "Dashboard User Engagement",
	  description: "Monitor user interactions and engagement levels to improve overall system activity.",
	  keyWords: ["dashboard engagement", "engagement", "user engagement"],
	  route: "/user-dashboards/user-engagement",
	},
	{
	  title: "Admin User Management",
	  description: "Oversee user accounts and manage transactions for seamless enterprise operations.",
	  keyWords: ["admin", "management", "user management"],
	  route: "/admin/user-management",
	},
	{
	  title: "Marketing In-App Campaign",
	  description: "Design and manage targeted in-app marketing campaigns for better user outreach.",
	  keyWords: ["in-app-campaign", "inappcampaign", "campaign", "upcoming events", "hello doctor", "recommended videos", "featured programs", "latest camps", "outstation/speciality clinic", "blogs"],
	  route: "/marketing/in-app-campaign",
	},
	{
	  title: "Department Details",
	  description: "Access detailed insights into departmental services, facilities, and technologies.",
	  keyWords: ["department services", "services", "department facility", "facility", "technology", "department technology", "condition", "department condition", "we treat", "department details"],
	  route: "/department-details",
	},
	{
	  title: "Education Overview",
	  description: "Get an overview of educational resources and initiatives for patient education.",
	  keyWords: ["education overview"],
	  route: "/patient-education/overview",
	},
	{
	  title: "Education Resources",
	  description: "Browse a comprehensive library of educational tools, FAQs, and reading materials.",
	  keyWords: ["gastro illness", "education resources", "treatments info", "health tools", "reading materials", "faqs", "frequently asked questions"],
	  route: "/patient-education/resources",
	},
	{
	  title: "Doctors List",
	  description: "Explore a detailed directory of available doctors for teleconsultation services.",
	  keyWords: ["doctors list"],
	  route: "/teleconsultation/virtual-management",
	},
	{
	  title: "Technical Support",
	  description: "Resolve issues efficiently by managing support tickets and categories.",
	  keyWords: ["technical support", "message"],
	  route: "/teleconsultation/technical-support",
	},
	{
	  title: "Create Survey",
	  description: "Develop and distribute surveys to collect feedback and insights from users.",
	  keyWords: ["create survey", "send notification", "notification system"],
	  route: "/feedback/create-survey",
	},
	{
	  title: "Patient Survey",
	  description: "View, analyze, and manage surveys focused on patient satisfaction and feedback.",
	  keyWords: ["patient survey"],
	  route: "/feedback/patient-surveys",
	},
	{
	  title: "News",
	  description: "Share the latest updates and announcements with users in a structured format.",
	  keyWords: ["new", "add news"],
	  route: "/news",
	},
	{
	  title: "Community Post",
	  description: "Engage with users through community posts and discussions on various topics.",
	  keyWords: ["community post"],
	  route: "/community-post",
	},
	{
	  title: "Medication Tracker",
	  description: "Track and manage medication schedules to ensure adherence to treatments.",
	  keyWords: ["medication tracker"],
	  route: "/medication-tracker",
	},
	{
	  title: "Chat",
	  description: "Facilitate communication through a streamlined chat interface for users and support.",
	  keyWords: ["chat"],
	  route: "/chat",
	},
	{
	  title: "Notification",
	  description: "Receive, manage, and configure system notifications in a centralized view.",
	  keyWords: ["notification"],
	  route: "/sidebar/notification",
	},
	{
	  title: "Settings",
	  description: "Adjust account preferences, access hospital details, and configure system settings.",
	  keyWords: ["settings", "account", "profile", "preferences", "terms and conditions", "about hospital", "hospital", "configurations"],
	  route: "/dashboard/settings",
	},
  ];
  