name: Deploy React App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Only Updated Files
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Detect changed files
      - name: Get Changed Files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'src/' | tr '\n' ' ')" >> $GITHUB_ENV

      # Step 3: Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Step 4: Build the application only if needed
      - name: Build the application
        if: env.CHANGED_FILES != ''
        run: CI=false npm run build

      # Step 5: Upload build artifacts if built
      - name: Upload Build Artifacts
        if: env.CHANGED_FILES != ''
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: build/

  deploy:
    name: Deploy Updated Files to Azure VM
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Download build artifacts if available
      - name: Download Build Artifacts
        if: success()
        uses: actions/download-artifact@v3
        with:
          name: react-app-build

      # Step 2: Setup SSH key and known hosts
      - name: Add SSH Key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
      - name: Add Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      # Step 3: Deploy only changed files using rsync
      - name: Upload Only Updated Files
        run: |
          rsync -avz --progress --exclude '.git/' --delete --files-from=<(git diff --name-only HEAD^ HEAD | grep 'build/') build/ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/react-app/

      # Step 4: Restart NGINX only if build updated
      - name: Restart NGINX If Needed
        if: env.CHANGED_FILES != ''
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
            sleep 5
