name: Deploy React App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Step 3: Build the React app
      - name: Build the application
        run: npm run build

      # Step 4: Upload build artifacts for reuse
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: build/

  deploy:
    name: Deploy React App to Azure VM
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-app-build

      # Step 2: Setup SSH key and known hosts
      - name: Add SSH Key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      # Step 3: Prepare Deployment Directory
      - name: Prepare Deployment Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/react-app/*
            sudo mkdir -p /var/www/react-app
            sudo chown -R $USER:$USER /var/www/react-app

      # Step 4: Upload Build Files
      - name: Upload Build Files
        run: |
          scp -i ~/.ssh/deploy_key -r react-app-build/* ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/react-app

      # Step 5: Restart NGINX
      - name: Restart NGINX
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
            sleep 5
