
name: Temp CI/CD for testing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React App to Azure VM
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Check Server Connection
        run: ssh -i ~/.ssh/deploy_key ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "echo 'SSH Connection Successful!'"
